---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: "{{ cookiecutter.role_name }}"
    image: ami-0f3497daebf127026
    instance_type: t3.large
    vpc_subnet_id: subnet-0a0c114d5a46ba1a6
    tags:
      Name: "{{ cookiecutter.role_name }}"
provisioner:
  name: ansible
verifier:
  name: ansible
