---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: "{{ cookiecutter.role_name }}-x86"
    image: ami-08f714c552929eda9 # Amazon Linux 2023
    instance_type: t3.large # x86
    vpc_subnet_id: subnet-0a0c114d5a46ba1a6
    tags:
      Name: "{{ cookiecutter.role_name }}-x86"
  - name: "{{ cookiecutter.role_name }}-arm"
    image: ami-0c47e5937c76232cd # Amazon Linux 2023
    instance_type: t4g.large # ARM
    vpc_subnet_id: subnet-0a0c114d5a46ba1a6
    tags:
      Name: "{{ cookiecutter.role_name }}-arm"
provisioner:
  name: ansible
verifier:
  name: ansible
